# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@adobe/css-tools-4.3.3" = {
      name = "_at_adobe_slash_css-tools";
      packageName = "@adobe/css-tools";
      version = "4.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@adobe/css-tools/-/css-tools-4.3.3.tgz";
        sha512 = "rE0Pygv0sEZ4vBWHlAgJLGDU7Pm8xoO6p3wsEceb7GYAjScrOHpEo8KK/eVkAcnSM+slAEtXjA2JpdjLp4fJQQ==";
      };
    };
    "@bufbuild/protobuf-2.7.0" = {
      name = "_at_bufbuild_slash_protobuf";
      packageName = "@bufbuild/protobuf";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@bufbuild/protobuf/-/protobuf-2.7.0.tgz";
        sha512 = "qn6tAIZEw5i/wiESBF4nQxZkl86aY4KoO0IkUa2Lh+rya64oTOdJQFlZuMwI1Qz9VBJQrQC4QlSA2DNek5gCOA==";
      };
    };
    "@isaacs/cliui-8.0.2" = {
      name = "_at_isaacs_slash_cliui";
      packageName = "@isaacs/cliui";
      version = "8.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@isaacs/cliui/-/cliui-8.0.2.tgz";
        sha512 = "O8jcjabXaleOG9DQ0+ARXWZBTfnP4WNAqzuiJK7ll44AmxGKv/J2M4TPjxjY3znBCfvBXFzucm1twdyFybFqEA==";
      };
    };
    "@jridgewell/gen-mapping-0.3.13" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.13.tgz";
        sha512 = "2kkt/7niJ6MgEPxF0bYdQ6etZaA+fQvDcLKckhy1yIQOzaoKjBBjSj63/aLVjYE3qhRt5dvM+uUyfCg6UKCBbA==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/source-map-0.3.11" = {
      name = "_at_jridgewell_slash_source-map";
      packageName = "@jridgewell/source-map";
      version = "0.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/source-map/-/source-map-0.3.11.tgz";
        sha512 = "ZMp1V8ZFcPG5dIWnQLr3NSI1MiCU7UETdS/A0G8V/XWHvJv3ZsFqutJn1Y5RPmAPX6F3BiE397OqveU/9NCuIA==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.5" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
        sha512 = "cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
      };
    };
    "@jridgewell/trace-mapping-0.3.30" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.30.tgz";
        sha512 = "GQ7Nw5G2lTu/BtHTKfXhKHok2WGetd4XYcVKGx00SjAk8GMwgJM3zr6zORiPGuOE+/vkc90KtTosSSvaCjKb2Q==";
      };
    };
    "@types/estree-1.0.8" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz";
        sha512 = "dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
      };
    };
    "@types/node-24.3.0" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "24.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-24.3.0.tgz";
        sha512 = "aPTXCrfwnDLj4VvXrm+UUCQjNEvJgNA8s5F1cvwQU+3KNltTOkBm1j30uNLyqqPNe7gE3KFzImYoZEfLhp4Yow==";
      };
    };
    "acorn-8.15.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
        sha512 = "NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-regex-6.2.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-6.2.0.tgz";
        sha512 = "TKY5pyBkHyADOPYlRT9Lx6F544mPl0vS5Ew7BJ45hA08Q+t3GjbueLliBWN3sMICk6+y7HdyxSzC4bWS8baBdg==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "ansi-styles-6.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-6.2.1.tgz";
        sha512 = "bN798gFfQX+viw3R7yrGWRqnrN2oRkEkUjjl4JNn4E8GxxbjtG3FbrEIIY3l8/hrwUwIeCZvi4QuOTP4MErVug==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-2.0.2" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.2.tgz";
        sha512 = "Jt0vHyM+jmUBqojB7E1NIYadt0vI0Qxjxd2TErW94wDz+E2LAm5vKMXXwg6ZZBTHPuUlDgQHKXvjGBdfcF1ZDQ==";
      };
    };
    "buffer-builder-0.2.0" = {
      name = "buffer-builder";
      packageName = "buffer-builder";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-builder/-/buffer-builder-0.2.0.tgz";
        sha512 = "7VPMEPuYznPSoR21NE1zvd2Xna6c/CloiZCfcMXR1Jny6PjX0N4Nsa38zcBFo/FMK+BlA+FLKbJCQ0i2yxp+Xg==";
      };
    };
    "buffer-from-1.1.2" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.2.tgz";
        sha512 = "E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==";
      };
    };
    "camelcase-8.0.0" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-8.0.0.tgz";
        sha512 = "8WB3Jcas3swSvjIeA2yvCJ+Miyz5l1ZmB6HFb9R1317dt9LCQoswg/BGrmAmkWVEszSrrg4RwmO46qIm2OEnSA==";
      };
    };
    "camelcase-keys-9.1.3" = {
      name = "camelcase-keys";
      packageName = "camelcase-keys";
      version = "9.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase-keys/-/camelcase-keys-9.1.3.tgz";
        sha512 = "Rircqi9ch8AnZscQcsA1C47NFdaO3wukpmIRzYcDOrmvgt78hM/sj5pZhZNec2NM12uk5vTwRHZ4anGcrC4ZTg==";
      };
    };
    "chokidar-4.0.3" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-4.0.3.tgz";
        sha512 = "Qgzu8kfBvo+cA4962jnP1KkS6Dop5NS6g7R5LFYJr4b8Ub94PPQXUksCw9PvXoeXPRRddRNC5C1JQUR2SMGtnA==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "colorjs.io-0.5.2" = {
      name = "colorjs.io";
      packageName = "colorjs.io";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colorjs.io/-/colorjs.io-0.5.2.tgz";
        sha512 = "twmVoizEW7ylZSN32OgKdXRmo1qg+wT5/6C3xu5b9QsWzSFAhHLn2xd8ro0diCsKfCj1RdaTP/nrcW+vAoQPIw==";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "copy-anything-2.0.6" = {
      name = "copy-anything";
      packageName = "copy-anything";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-anything/-/copy-anything-2.0.6.tgz";
        sha512 = "1j20GZTsvKNkc4BY3NpMOM8tt///wY3FpIzozTOFO2ffuZcV61nojHXVKIy3WM+7ADCy5FVhdZYHYDdgTU0yJw==";
      };
    };
    "cross-spawn-7.0.6" = {
      name = "cross-spawn";
      packageName = "cross-spawn";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn/-/cross-spawn-7.0.6.tgz";
        sha512 = "uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==";
      };
    };
    "debug-4.4.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.1.tgz";
        sha512 = "KcKCqiftBJcZr++7ykoDIEwSa3XWowTfNPo92BYxjXiyYEVrUQh2aLyhxBCwww+heortUFxEJYcRzosstTEBYQ==";
      };
    };
    "detect-libc-2.0.4" = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.4.tgz";
        sha512 = "3UDv+G9CsCKO1WKMGw9fwq/SWJYbI0c5Y7LU1AXYoDdbhE2AHQ6N6Nb34sG8Fj7T5APy8qXDCKuuIHd1BR0tVA==";
      };
    };
    "eastasianwidth-0.2.0" = {
      name = "eastasianwidth";
      packageName = "eastasianwidth";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/eastasianwidth/-/eastasianwidth-0.2.0.tgz";
        sha512 = "I88TYZWc9XiYHRQ4/3c5rjjfgkjhLyW2luGIheGERbNQ6OY7yTybanSpDXZa8y7VUP9YmDcYa+eyq4ca7iLqWA==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "emoji-regex-9.2.2" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "9.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-9.2.2.tgz";
        sha512 = "L18DaJsXSUk2+42pv8mLs5jJT2hqFkFE4j21wOmgbUqsZ2hL72NsUU785g9RXgo3s0ZNgVl42TiHp3ZtOv/Vyg==";
      };
    };
    "esbuild-0.25.9" = {
      name = "esbuild";
      packageName = "esbuild";
      version = "0.25.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/esbuild/-/esbuild-0.25.9.tgz";
        sha512 = "CRbODhYyQx3qp7ZEwzxOk4JBqmD/seJrzPa/cGjY1VtIn5E09Oi9/dB4JwctnfZ8Q8iT7rioVv5k/FNT/uf54g==";
      };
    };
    "fdir-6.5.0" = {
      name = "fdir";
      packageName = "fdir";
      version = "6.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz";
        sha512 = "tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
      };
    };
    "foreground-child-3.3.1" = {
      name = "foreground-child";
      packageName = "foreground-child";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreground-child/-/foreground-child-3.3.1.tgz";
        sha512 = "gIXjKqtFuWEgzFRJA9WCQeSJLZDjgJUOMCMzxtvFq/37KojM1BFGufqsCy0r4qSQmYLsZYMeyRqzIWOMup03sw==";
      };
    };
    "fuse.js-7.1.0" = {
      name = "fuse.js";
      packageName = "fuse.js";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fuse.js/-/fuse.js-7.1.0.tgz";
        sha512 = "trLf4SzuuUxfusZADLINj+dE8clK1frKdmqiJNb1Es75fmI5oY6X2mxLVUciLLjxqw/xr72Dhy+lER6dGd02FQ==";
      };
    };
    "get-tsconfig-4.10.1" = {
      name = "get-tsconfig";
      packageName = "get-tsconfig";
      version = "4.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-tsconfig/-/get-tsconfig-4.10.1.tgz";
        sha512 = "auHyJ4AgMz7vgS8Hp3N6HXSmlMdUyhSUrfBF16w153rxtLIEOE+HGqaBppczZvnHLqQJfiHotCYpNhl0lUROFQ==";
      };
    };
    "glob-10.4.5" = {
      name = "glob";
      packageName = "glob";
      version = "10.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-10.4.5.tgz";
        sha512 = "7Bv8RF0k6xjo7d4A/PxYLbUCfb6c+Vpd2/mB2yRDlew7Jb5hEXiCD9ibfO7wpk8i4sevK6DFny9h7EYbM3/sHg==";
      };
    };
    "globals-16.3.0" = {
      name = "globals";
      packageName = "globals";
      version = "16.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-16.3.0.tgz";
        sha512 = "bqWEnJ1Nt3neqx2q5SFfGS8r/ahumIakg3HcwtNlrVlwXIeNumWn/c7Pn/wKzGhf6SaW6H6uWXLqC30STCMchQ==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "immutable-5.1.3" = {
      name = "immutable";
      packageName = "immutable";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-5.1.3.tgz";
        sha512 = "+chQdDfvscSF1SJqv2gn4SRO2ZyS3xL3r7IW/wWEEzrzLisnOlKiQu5ytC/BVNcS15C39WT2Hg/bjKjDMcu+zg==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-what-3.14.1" = {
      name = "is-what";
      packageName = "is-what";
      version = "3.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-what/-/is-what-3.14.1.tgz";
        sha512 = "sNxgpk9793nzSs7bA6JQJGeIuRBQhAaNGG77kzYQgMkrID+lS6SlK07K5LaptscDlSaIgH+GPFzf+d75FVxozA==";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha512 = "RHxMLp9lnKHGHRng9QFhRCMbYAcVpn69smSGcq3f36xjgVVWThj4qqLbTLlq7Ssj8B+fIQ1EuCEGI2lKsyQeIw==";
      };
    };
    "jackspeak-3.4.3" = {
      name = "jackspeak";
      packageName = "jackspeak";
      version = "3.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/jackspeak/-/jackspeak-3.4.3.tgz";
        sha512 = "OGlZQpz2yfahA/Rd1Y8Cd9SIEsqvXkLVoSw/cgwhnhFMDbsQFeZYoJJ7bIZBS9BcamUW96asq/npPWugM+RQBw==";
      };
    };
    "jiti-2.5.1" = {
      name = "jiti";
      packageName = "jiti";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-2.5.1.tgz";
        sha512 = "twQoecYPiVA5K/h6SxtORw/Bs3ar+mLUtoPSc7iMXzQzK8d7eJ/R09wmTwAjiamETn1cXYPGfNnu7DMoHgu12w==";
      };
    };
    "less-4.4.1" = {
      name = "less";
      packageName = "less";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/less/-/less-4.4.1.tgz";
        sha512 = "X9HKyiXPi0f/ed0XhgUlBeFfxrlDP3xR4M7768Zl+WXLUViuL9AOPPJP4nCV0tgRWvTYvpNmN0SFhZOQzy16PA==";
      };
    };
    "lightningcss-1.30.1" = {
      name = "lightningcss";
      packageName = "lightningcss";
      version = "1.30.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss/-/lightningcss-1.30.1.tgz";
        sha512 = "xi6IyHML+c9+Q3W0S4fCQJOym42pyurFiJUHEcEyHS0CeKzia4yZDEsLlqOFykxOdHpNy0NmvVO31vcSqAxJCg==";
      };
    };
    "lru-cache-10.4.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "10.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-10.4.3.tgz";
        sha512 = "JNAzZcXrCt42VGLuYz0zfAzDfAvJWW6AfYlDBQyDV5DClI2m5sAmK+OIO7s59XfsRsWHp02jAJrRadPRGTt6SQ==";
      };
    };
    "map-obj-5.0.0" = {
      name = "map-obj";
      packageName = "map-obj";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-obj/-/map-obj-5.0.0.tgz";
        sha512 = "2L3MIgJynYrZ3TYMriLDLWocz15okFakV6J12HXvMXDHui2x/zgChzg1u9mFFGbbGWE+GsLpQByt4POb9Or+uA==";
      };
    };
    "minimatch-9.0.5" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "9.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-9.0.5.tgz";
        sha512 = "G6T0ZX48xgozx7587koeX9Ys2NYy6Gmv//P89sEte9V9whIapMNF4idKxnW2QtCcLiTWlb/wfCabAtAFWhhBow==";
      };
    };
    "minipass-7.1.2" = {
      name = "minipass";
      packageName = "minipass";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minipass/-/minipass-7.1.2.tgz";
        sha512 = "qOOzS1cBTWYF4BH8fVePDBOO9iptMnGUEZwNc/cMWnTV2nVLZ7VoNWEPHkYczZA0pdoA7dl6e7FL659nX9S2aw==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "nanoid-3.3.11" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "3.3.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-3.3.11.tgz";
        sha512 = "N8SpfPUnUp1bK+PMYW8qSWdl9U+wwNWI4QKxOYDy9JAro3WMX7p2OeVRF9v+347pnakNevPmiHhNmZ2HbFA76w==";
      };
    };
    "package-json-from-dist-1.0.1" = {
      name = "package-json-from-dist";
      packageName = "package-json-from-dist";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/package-json-from-dist/-/package-json-from-dist-1.0.1.tgz";
        sha512 = "UEZIS3/by4OC8vL3P2dTXRETpebLI2NiI5vIrjaD/5UtrkFX/tNbwjTSRAGC/+7CAo2pIcBaRgWmcBBHcsaCIw==";
      };
    };
    "parse-node-version-1.0.1" = {
      name = "parse-node-version";
      packageName = "parse-node-version";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-node-version/-/parse-node-version-1.0.1.tgz";
        sha512 = "3YHlOa/JgH6Mnpr05jP9eDG254US9ek25LyIxZlDItp2iJtwyaXQb57lBYLdT3MowkUFYEV2XXNAYIPlESvJlA==";
      };
    };
    "path-key-3.1.1" = {
      name = "path-key";
      packageName = "path-key";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-3.1.1.tgz";
        sha512 = "ojmeN0qd+y0jszEtoY48r0Peq5dwMEkIlCOu6Q5f41lfkswXuKtYrhgoTpLnyIcHm24Uhqx+5Tqm2InSwLhE6Q==";
      };
    };
    "path-scurry-1.11.1" = {
      name = "path-scurry";
      packageName = "path-scurry";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-scurry/-/path-scurry-1.11.1.tgz";
        sha512 = "Xa4Nw17FS9ApQFJ9umLiJS4orGjm7ZzwUrwamcGQuHSzDyth9boKDaycYdDcZDuqYATXw4HFXgaqWTctW/v1HA==";
      };
    };
    "picocolors-1.1.1" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
        sha512 = "xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
      };
    };
    "picomatch-4.0.3" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz";
        sha512 = "5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==";
      };
    };
    "postcss-8.5.6" = {
      name = "postcss";
      packageName = "postcss";
      version = "8.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-8.5.6.tgz";
        sha512 = "3Ybi1tAuwAP9s0r1UQ2J4n5Y0G05bJkpUIO0/bI9MhwmD70S5aTWbXGBwxHrelT+XM1k6dM0pk+SwNkpTRN7Pg==";
      };
    };
    "quick-lru-6.1.2" = {
      name = "quick-lru";
      packageName = "quick-lru";
      version = "6.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/quick-lru/-/quick-lru-6.1.2.tgz";
        sha512 = "AAFUA5O1d83pIHEhJwWCq/RQcRukCkn/NSm2QsTEMle5f2hP0ChI2+3Xb051PZCkLryI/Ir1MVKviT2FIloaTQ==";
      };
    };
    "react-19.1.1" = {
      name = "react";
      packageName = "react";
      version = "19.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-19.1.1.tgz";
        sha512 = "w8nqGImo45dmMIfljjMwOGtbmC/mk4CMYhWIicdSflH91J9TyCyczcPFXJzrZ/ZXcgGRFeP6BU0BEJTw6tZdfQ==";
      };
    };
    "react-dom-19.1.1" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "19.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-19.1.1.tgz";
        sha512 = "Dlq/5LAZgF0Gaz6yiqZCf6VCcZs1ghAJyrsu84Q/GT0gV+mCxbfmKNoGRKBYMJ8IEdGPqu49YWXD02GCknEDkw==";
      };
    };
    "react-icons-5.5.0" = {
      name = "react-icons";
      packageName = "react-icons";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-icons/-/react-icons-5.5.0.tgz";
        sha512 = "MEFcXdkP3dLo8uumGI5xN3lDFNsRtrjbOEKDLD7yv76v4wpnEq2Lt2qeHaQOr34I/wPN3s3+N08WkQ+CW37Xiw==";
      };
    };
    "readdirp-4.1.2" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-4.1.2.tgz";
        sha512 = "GDhwkLfywWL2s6vEjyhri+eXmfH6j1L7JE27WhqLeYzoh/A3DBaYGEj2H/HFZCn/kMfim73FXxEJTw06WtxQwg==";
      };
    };
    "resolve-pkg-maps-1.0.0" = {
      name = "resolve-pkg-maps";
      packageName = "resolve-pkg-maps";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-pkg-maps/-/resolve-pkg-maps-1.0.0.tgz";
        sha512 = "seS2Tj26TBVOC2NIc2rOe2y2ZO7efxITtLZcGSOnHHNOQ7CkiUBfw0Iw2ck6xkIhPwLhKNLS8BO+hEpngQlqzw==";
      };
    };
    "rollup-4.48.1" = {
      name = "rollup";
      packageName = "rollup";
      version = "4.48.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-4.48.1.tgz";
        sha512 = "jVG20NvbhTYDkGAty2/Yh7HK6/q3DGSRH4o8ALKGArmMuaauM9kLfoMZ+WliPwA5+JHr2lTn3g557FxBV87ifg==";
      };
    };
    "rxjs-7.8.2" = {
      name = "rxjs";
      packageName = "rxjs";
      version = "7.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rxjs/-/rxjs-7.8.2.tgz";
        sha512 = "dhKf903U/PQZY6boNNtAGdWbG85WAbjT/1xYoZIC7FAY0yWapOBQVsVrDl58W86//e1VpMNBtRV4MaXfdMySFA==";
      };
    };
    "sass-1.90.0" = {
      name = "sass";
      packageName = "sass";
      version = "1.90.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass/-/sass-1.90.0.tgz";
        sha512 = "9GUyuksjw70uNpb1MTYWsH9MQHOHY6kwfnkafC24+7aOMZn9+rVMBxRbLvw756mrBFbIsFg6Xw9IkR2Fnn3k+Q==";
      };
    };
    "sass-embedded-1.90.0" = {
      name = "sass-embedded";
      packageName = "sass-embedded";
      version = "1.90.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass-embedded/-/sass-embedded-1.90.0.tgz";
        sha512 = "XP1EltyLLfuU5FsGVjSz8PcT925oA3rDnJTWOEBHR42k62ZEbKTcZ4gVlFwKi0Ggzi5E8v1K2BplD8ELHwusYg==";
      };
    };
    "sax-1.4.1" = {
      name = "sax";
      packageName = "sax";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.4.1.tgz";
        sha512 = "+aWOz7yVScEGoKNd4PA10LZ8sk0A/z5+nXQG5giUO5rprX9jgYsTdov9qCchZiPIZezbZH+jRut8nPodFAX4Jg==";
      };
    };
    "scheduler-0.26.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.26.0.tgz";
        sha512 = "NlHwttCI/l5gCPR3D1nNXtWABUmBwvZpEQiD4IXSbIDq8BzLIK/7Ir5gTFSGZDUu37K5cMNp0hFtzO38sC7gWA==";
      };
    };
    "shebang-command-2.0.0" = {
      name = "shebang-command";
      packageName = "shebang-command";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-command/-/shebang-command-2.0.0.tgz";
        sha512 = "kHxr2zZpYtdmrN1qDjrrX/Z1rR1kG8Dx+gkpK1G4eXmvXswmcE1hTWBWYUzlraYw1/yZp6YuDY77YtvbN0dmDA==";
      };
    };
    "shebang-regex-3.0.0" = {
      name = "shebang-regex";
      packageName = "shebang-regex";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/shebang-regex/-/shebang-regex-3.0.0.tgz";
        sha512 = "7++dFhtcx3353uBaq8DDR4NuxBetBzC7ZQOhmTQInHEd6bSrXdiEyzCvG07Z44UYdLShWUyXt5M/yhz8ekcb1A==";
      };
    };
    "signal-exit-4.1.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-4.1.0.tgz";
        sha512 = "bzyZ1e88w9O1iNJbKnOlvYTrWPDl46O1bG0D3XInv+9tkPrxrN8jUUTiFlDkkmKWgn1M6CfIA13SuGqOa9Korw==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-0.7.6" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.7.6.tgz";
        sha512 = "i5uvt8C3ikiWeNZSVZNWcfZPItFQOsYTUAOkcUPGd8DqDy1uOUikjt5dG+uRlwyvR108Fb9DOd4GvXfT0N2/uQ==";
      };
    };
    "source-map-js-1.2.1" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.2.1.tgz";
        sha512 = "UXWMKhLOwVKb728IUtQPXxfYU+usdybtUrK/8uGE8CQMvrhOpwvzDBwj0QhSL7MQc7vIsISBG8VQ8+IDQxpfQA==";
      };
    };
    "source-map-support-0.5.21" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.21.tgz";
        sha512 = "uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string-width-5.1.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-5.1.2.tgz";
        sha512 = "HnLOCR3vjcY8beoNLtcjZ5/nxn2afmME6lhrDrebokqMap+XbeW8n9TXpPDOqdGK5qcI3oT0GKTW6wC7EMiVqA==";
      };
    };
    "string-width-cjs-4.2.3" = {
      name = "string-width-cjs";
      packageName = "string-width-cjs";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strip-ansi-7.1.0" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-7.1.0.tgz";
        sha512 = "iq6eVVI64nQQTRYq2KtEg2d2uU7LElhTJwsH4YzIHZshxlgZms/wIc4VoDQTlG/IvVIrBKG06CrZnp0qv7hkcQ==";
      };
    };
    "strip-ansi-cjs-6.0.1" = {
      name = "strip-ansi-cjs";
      packageName = "strip-ansi-cjs";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "stylus-0.64.0" = {
      name = "stylus";
      packageName = "stylus";
      version = "0.64.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylus/-/stylus-0.64.0.tgz";
        sha512 = "ZIdT8eUv8tegmqy1tTIdJv9We2DumkNZFdCF5mz/Kpq3OcTaxSuCAYZge6HKK2CmNC02G1eJig2RV7XTw5hQrA==";
      };
    };
    "sugarss-5.0.1" = {
      name = "sugarss";
      packageName = "sugarss";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sugarss/-/sugarss-5.0.1.tgz";
        sha512 = "ctS5RYCBVvPoZAnzIaX5QSShK8ZiZxD5HUqSxlusvEMC+QZQIPCPOIJg6aceFX+K2rf4+SH89eu++h1Zmsr2nw==";
      };
    };
    "supports-color-8.1.1" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "8.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-8.1.1.tgz";
        sha512 = "MpUEN2OodtUzxvKQl72cUF7RQ5EiHsGvSsVG0ia9c5RbWGL2CI4C7EpPS8UTBIplnlzZiNuV56w+FuNxy3ty2Q==";
      };
    };
    "sync-child-process-1.0.2" = {
      name = "sync-child-process";
      packageName = "sync-child-process";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sync-child-process/-/sync-child-process-1.0.2.tgz";
        sha512 = "8lD+t2KrrScJ/7KXCSyfhT3/hRq78rC0wBFqNJXv3mZyn6hW2ypM05JmlSvtqRbeq6jqA94oHbxAr2vYsJ8vDA==";
      };
    };
    "sync-message-port-1.1.3" = {
      name = "sync-message-port";
      packageName = "sync-message-port";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sync-message-port/-/sync-message-port-1.1.3.tgz";
        sha512 = "GTt8rSKje5FilG+wEdfCkOcLL7LWqpMlr2c3LRuKt/YXxcJ52aGSbGBAdI4L3aaqfrBt6y711El53ItyH1NWzg==";
      };
    };
    "terser-5.43.1" = {
      name = "terser";
      packageName = "terser";
      version = "5.43.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/terser/-/terser-5.43.1.tgz";
        sha512 = "+6erLbBm0+LROX2sPXlUYx/ux5PyE9K/a92Wrt6oA+WDAoFTdpHE5tCYCI5PNzq2y8df4rA+QgHLJuR4jNymsg==";
      };
    };
    "tinyglobby-0.2.14" = {
      name = "tinyglobby";
      packageName = "tinyglobby";
      version = "0.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinyglobby/-/tinyglobby-0.2.14.tgz";
        sha512 = "tX5e7OM1HnYr2+a2C/4V0htOcSQcoSTH9KgJnVvNm5zm/cyEWKJ7j7YutsH9CxMdtOkkLFy2AHrMci9IM8IPZQ==";
      };
    };
    "tslib-2.8.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
        sha512 = "oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
      };
    };
    "tsx-4.20.5" = {
      name = "tsx";
      packageName = "tsx";
      version = "4.20.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tsx/-/tsx-4.20.5.tgz";
        sha512 = "+wKjMNU9w/EaQayHXb7WA7ZaHY6hN8WgfvHNQ3t1PnU91/7O8TcTnIhCDYTZwnt8JsO9IBqZ30Ln1r7pPF52Aw==";
      };
    };
    "type-fest-4.41.0" = {
      name = "type-fest";
      packageName = "type-fest";
      version = "4.41.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-fest/-/type-fest-4.41.0.tgz";
        sha512 = "TeTSQ6H5YHvpqVwBRcnLDCBnDOHWYu7IvGbHT6N8AOymcr9PJGjc1GTtiWZTYg0NCgYwvnYWEkVChQAr9bjfwA==";
      };
    };
    "typescript-5.8.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.8.3.tgz";
        sha512 = "p1diW6TqL9L07nNxvRMM7hMMw4c5XOo/1ibL4aAIGmSAt9slTE1Xgw5KWuof2uTOvCg9BY7ZRi+GaF+7sfgPeQ==";
      };
    };
    "undici-types-7.10.0" = {
      name = "undici-types";
      packageName = "undici-types";
      version = "7.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici-types/-/undici-types-7.10.0.tgz";
        sha512 = "t5Fy/nfn+14LuOc2KNYg75vZqClpAiqscVvMygNnlsHBFpSXdJaYtXMcdNLpl/Qvc3P2cB3s6lOV51nqsFq4ag==";
      };
    };
    "varint-6.0.0" = {
      name = "varint";
      packageName = "varint";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/varint/-/varint-6.0.0.tgz";
        sha512 = "cXEIW6cfr15lFv563k4GuVuW/fiwjknytD37jIOLSdSWuOI6WnO/oKwmP2FQTU2l01LP8/M5TSAJpzUaGe3uWg==";
      };
    };
    "vite-7.1.3" = {
      name = "vite";
      packageName = "vite";
      version = "7.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vite/-/vite-7.1.3.tgz";
        sha512 = "OOUi5zjkDxYrKhTV3V7iKsoS37VUM7v40+HuwEmcrsf11Cdx9y3DIr2Px6liIcZFwt3XSRpQvFpL3WVy7ApkGw==";
      };
    };
    "which-2.0.2" = {
      name = "which";
      packageName = "which";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-2.0.2.tgz";
        sha512 = "BLI3Tl1TW3Pvl70l3yq3Y64i+awpwXqsGBYWkkqMtnbXgrMD+yj7rhW0kuEDxzJaYXGjEW5ogapKNMEKNMjibA==";
      };
    };
    "wrap-ansi-8.1.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-8.1.0.tgz";
        sha512 = "si7QWI6zUMq56bESFvagtmzMdGOtoxfR+Sez11Mobfc7tm+VkUckk9bW2UeffTGVUbOksxmSw0AA2gs8g71NCQ==";
      };
    };
    "wrap-ansi-cjs-7.0.0" = {
      name = "wrap-ansi-cjs";
      packageName = "wrap-ansi-cjs";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "yaml-2.8.1" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.8.1.tgz";
        sha512 = "lcYcMxX2PO9XMGvAJkJ3OsNMw+/7FKes7/hgerGUYWIoWu5j/+YQqcZr5JnPZWzOsEBgMbSbiSTn/dv/69Mkpw==";
      };
    };
  };
  args = {
    name = "gearshift";
    packageName = "gearshift";
    version = "0.0.0";
    src = ./.;
    dependencies = [
      sources."@adobe/css-tools-4.3.3"
      sources."@bufbuild/protobuf-2.7.0"
      sources."@isaacs/cliui-8.0.2"
      sources."@jridgewell/gen-mapping-0.3.13"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/source-map-0.3.11"
      sources."@jridgewell/sourcemap-codec-1.5.5"
      sources."@jridgewell/trace-mapping-0.3.30"
      sources."@types/estree-1.0.8"
      sources."@types/node-24.3.0"
      sources."acorn-8.15.0"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-6.2.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-2.0.2"
      sources."buffer-builder-0.2.0"
      sources."buffer-from-1.1.2"
      sources."camelcase-8.0.0"
      sources."camelcase-keys-9.1.3"
      sources."chokidar-4.0.3"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."colorjs.io-0.5.2"
      sources."commander-2.20.3"
      sources."copy-anything-2.0.6"
      sources."cross-spawn-7.0.6"
      sources."debug-4.4.1"
      sources."detect-libc-2.0.4"
      sources."eastasianwidth-0.2.0"
      sources."emoji-regex-9.2.2"
      sources."esbuild-0.25.9"
      sources."fdir-6.5.0"
      sources."foreground-child-3.3.1"
      sources."fuse.js-7.1.0"
      sources."get-tsconfig-4.10.1"
      sources."glob-10.4.5"
      sources."globals-16.3.0"
      sources."has-flag-4.0.0"
      sources."immutable-5.1.3"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-what-3.14.1"
      sources."isexe-2.0.0"
      sources."jackspeak-3.4.3"
      sources."jiti-2.5.1"
      sources."less-4.4.1"
      sources."lightningcss-1.30.1"
      sources."lru-cache-10.4.3"
      sources."map-obj-5.0.0"
      sources."minimatch-9.0.5"
      sources."minipass-7.1.2"
      sources."ms-2.1.3"
      sources."nanoid-3.3.11"
      sources."package-json-from-dist-1.0.1"
      sources."parse-node-version-1.0.1"
      sources."path-key-3.1.1"
      sources."path-scurry-1.11.1"
      sources."picocolors-1.1.1"
      sources."picomatch-4.0.3"
      sources."postcss-8.5.6"
      sources."quick-lru-6.1.2"
      sources."react-19.1.1"
      sources."react-dom-19.1.1"
      sources."react-icons-5.5.0"
      sources."readdirp-4.1.2"
      sources."resolve-pkg-maps-1.0.0"
      sources."rollup-4.48.1"
      sources."rxjs-7.8.2"
      sources."sass-1.90.0"
      sources."sass-embedded-1.90.0"
      sources."sax-1.4.1"
      sources."scheduler-0.26.0"
      sources."shebang-command-2.0.0"
      sources."shebang-regex-3.0.0"
      sources."signal-exit-4.1.0"
      sources."source-map-0.7.6"
      sources."source-map-js-1.2.1"
      (sources."source-map-support-0.5.21" // {
        dependencies = [
          sources."source-map-0.6.1"
        ];
      })
      sources."string-width-5.1.2"
      (sources."string-width-cjs-4.2.3" // {
        dependencies = [
          sources."emoji-regex-8.0.0"
          sources."strip-ansi-6.0.1"
        ];
      })
      (sources."strip-ansi-7.1.0" // {
        dependencies = [
          sources."ansi-regex-6.2.0"
        ];
      })
      sources."strip-ansi-cjs-6.0.1"
      sources."stylus-0.64.0"
      sources."sugarss-5.0.1"
      sources."supports-color-8.1.1"
      sources."sync-child-process-1.0.2"
      sources."sync-message-port-1.1.3"
      sources."terser-5.43.1"
      sources."tinyglobby-0.2.14"
      sources."tslib-2.8.1"
      sources."tsx-4.20.5"
      sources."type-fest-4.41.0"
      sources."typescript-5.8.3"
      sources."undici-types-7.10.0"
      sources."varint-6.0.0"
      sources."vite-7.1.3"
      sources."which-2.0.2"
      sources."wrap-ansi-8.1.0"
      (sources."wrap-ansi-cjs-7.0.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."emoji-regex-8.0.0"
          sources."string-width-4.2.3"
          sources."strip-ansi-6.0.1"
        ];
      })
      sources."yaml-2.8.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
